### ISSUE TITLE
Create policy to delete resources created by prometheus-collector after AKS clusters delete.

### ISSUE THREAD

**Issue by theok-nice** [Azure/prometheus-collector#746]
Using the process described  in here https://github.com/Azure/prometheus-collector/tree/main/AddonPolicyTemplate, we can create a policy to monitor AKS clusters. 

But when user deletes the AKS cluster, the resources created by this policy ie 
```
Data collection endpoint,
Data collection rule,
Prometheus rule group (preview)
```
are not getting deleted.

Can you please provide a policy (or some other automated process) that will delete all three type of resources, when the AKS cluster doesn't exist anymore?

**Comment by vishiy** [comment]
Hi @theok-nice - Thanks for the feedback. we will look into this and possibly provide a cleanup script for the resources created by policy, and also document them...

**Comment by theok-nice** [comment]
@vishiy do you have an estimate when to expect this kind of solution?

**Comment by vishiy** [comment]
Hi @theok-nice - Currently, the plan is to ensure that the CLI way of disabling (documented here -- https://learn.microsoft.com/en-us/azure/azure-monitor/containers/kubernetes-monitoring-disable#disable-prometheus) can be used for disablement irrespective of the mechanism (ux, cli, arm, policy, terraform, bicep etc...) used to enable azure prometheus . We just need to adjust a few names of objects we create during those creates , so that CLI disablement looks for the same name & deletes/cleans them up. We will work on it next sprint (april 2024). Will keep this issue open until we push out those updates..

**Comment by Sohamdg081992** [comment]
@vishiy Thanks! I have added an item in this sprint to work on this.

**Comment by Sohamdg081992** [comment]
Hi @theok-nice , please use the CLI way of disabling (documented here -- https://learn.microsoft.com/en-us/azure/azure-monitor/containers/kubernetes-monitoring-disable#disable-prometheus) Azure Managed Prometheus to delete the mentioned  resources created by this policy. Just deleting the cluster will not delete the other addon related resources from the resource group. I have validated that CLI disablement works irrespective of the mechanism (ux, cli, arm, policy, terraform, bicep etc...) used to enable azure prometheus. Closing this issue, please feel free to re-open if you have additional questions.
