### ISSUE TITLE
Missing recommended alerts

### ISSUE THREAD

**Issue by braieralves** [Azure/prometheus-collector#791]
Cx is migrating from Custom metrics alerts (retiring on 5/31/2024) to Prometheus alerts.
In below docs, https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-metric-alerts?tabs=arm-template%2Cazure-portal#recommended-alert-rules

**Code:** https://[raw.githubusercontent.com/Azure/prometheus-collector/main/GeneratedMonitoringArtifacts/Default/recommendedMetricAlerts.json](https://raw.githubusercontent.com/Azure/prometheus-collector/main/GeneratedMonitoringArtifacts/Default/recommendedMetricAlerts.json)
 
It is given that source code is available in GitHub but for few recommended alerts like CPU and disk of nodes as highlighted below, it is not there in GitHub as we checked. Cx needs the source code to complete deployments.
![image](https://github.com/Azure/prometheus-collector/assets/38931377/951c065a-56bf-4f19-9c87-f3b73c7b5e4c)

**Comment by jmelching** [comment]
I need this as well.

**Comment by vishiy** [comment]
Hi @braieralves - we have revamped recommended/default alerts (alerts, experiences &  docs), as of last week. Please let us know if this issue is still something you want us to investigate.

**Comment by Sohamdg081992** [comment]
Hi @braieralves , since we have updated both the documentation and source code, the respective alerts (shown in screenshot) 
 have been updated and they now show up both in the Github and doc. I am closing this issue. Please feel free to reopen the issue if you have other concerns/ want us to investigate.
<img width="456" alt="image" src="https://github.com/Azure/prometheus-collector/assets/31517098/3ac0677e-4cc4-4db4-b3ad-5342b44e85a0">
<img width="440" alt="image" src="https://github.com/Azure/prometheus-collector/assets/31517098/cf842ee3-75e9-4a10-8237-5e72e23bea17">
